- hosts: app-servers
  gather_facts: false
  become: true
  roles:
  - role: tomcat
    tags: tomcat

- hosts: all
  gather_facts: true
  become: true
  roles:
  - role: common
    tags: common

- hosts: load-balancers
  become: true
  roles:
  - role: haproxy
    tags: haproxy
